### PR TITLE
Cipher Algo's Contribution 

### PR DESCRIPTION
**Pull request by CipherAlgo-19**
I have made some changes in main java file to find the given is odd or even and updated those details in read Me txt file. So check it and merge my contribution in your main repository.

### CODE REVIEW

**Comment by raghulrmk** [comment]
Don't Update anything on the read me text file. Because it just to check what we are doing in this directory/repository.
Just update it my boy!!!!!

Just do this.

**Comment by CipherAlgo-19** [comment]
Did as you said

**Comment by raghulrmk** [comment]
I am sorry to say that go with the previous commit and update what you have did in read me text file!!!

**Comment by CipherAlgo-19** [comment]
Just reset my old commit

**Comment by CipherAlgo-19** [comment]
now merge it please

**Comment by raghulrmk** [comment]
Merged you pull request in my own repository.

Thanks for your contribution Cipher Algo!!!!

**Comment by CipherAlgo-19** [comment]
Thank you

**Pull request merged**
